### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by wesoos** [mpilone/timeline-vaadin#1]
Hi, is this available as a maven dependency?  Or how would I go about adding the timeline to my project?

Thanks
Wessel

**Comment by mpilone** [comment]
I don't have the archives in the central repository but I host them in the Git repository mpilone/mvn-repo. You can add the repository to your POM:

```
<repositories>
     <repository>
         <id>mpilone-snapshots</id>
         <url>https://github.com/mpilone/mvn-repo/raw/master/snapshots</url>
     </repository>
     <repository>
         <id>mpilone-releases</id>
         <url>https://github.com/mpilone/mvn-repo/raw/master/releases</url>
     </repository>
 </repositories>
```
